--INSERT INTO genres (name, route) VALUES ('Romantické', 'romance')
--INSERT INTO genres (name, route) VALUES ('Mysteriózne', 'mystery')
--INSERT INTO genres (name, route) VALUES ('Dobrodružné', 'adventure')
--INSERT INTO genres (name, route) VALUES ('Biografické', 'biographies')
--INSERT INTO genres (name, route) VALUES ('Historické', 'history')
--INSERT INTO genres (name, route) VALUES ('Detské', 'childrens')
--INSERT INTO genres (name, route) VALUES ('Fantasy', 'fantasy')
--NSERT INTO genres (name, route) VALUES ('Science fiction', 'scifi')
INSERT INTO genres (name, route) VALUES ('Horor', 'horror')